### ISSUE TITLE
How to resume a PRNG, at a later time deterministically?

### ISSUE THREAD

**Issue by UnderTheCarpet** [robojeb/pcg_rand#1]
How can I access and save the state in a way, that I can resume the pseudo random number generator at a later time?

**Comment by UnderTheCarpet** [comment]
As a workaround I've implemented a method for a PcgEngine<IType,...>

``` rust
impl<Itype, Xtype, MulMix, OutMix> PcgEngine<Itype, Xtype, SpecificSeqStream<Itype>, MulMix, OutMix>
    where Itype: PcgOps + BitSize + Clone,
          Xtype: PcgOps + BitSize,
          MulMix: Multiplier<Itype>,
          OutMix: OutputMixin<Itype, Xtype>,
          SpecificSeqStream<Itype>: Stream<Itype>,
          PcgEngine<Itype, Xtype, SpecificSeqStream<Itype>, MulMix, OutMix>: Rng
{
    pub fn extract_seed(&self) -> [Itype; 2] {
        [self.state.clone(), self.stream_mix.get_stream()]
    }
}
```

I'm not sure, if your interested in adding something like this also for the other subtypes? In the long run, it would be probably wise to add something like `extract_seed()` to the `SeedableRng` trait in the `rand` crate.

**Comment by UnderTheCarpet** [comment]
Also see rust-lang-nursery/rand#84.

**Comment by robojeb** [comment]
@fkjogu sorry for not getting back to you. These past few months have been a whirlwind involving moving and starting a new job. 

I like this idea, I toyed with serializing the generators in the "serde" branch. 
If you want to submit a pull request for this I would be happy to include it in the library. 

If you don't have time, I will get around to implementing it myself sometime soon hopefully.
