### ISSUE TITLE
128-bit integers are available in nightly Rust

### ISSUE THREAD

**Issue by FaultyRAM** [robojeb/pcg_rand#2]
`u128` and `i128` were added in rust-lang/rust/pull/38482. They're currently behind the `i128_type` feature gate.

**Comment by robojeb** [comment]
I have looked into supporting rust native u128 on nightly but there are some issues with the Rand crate not supporting rand for u128. This prevents implementing Rand for PCG which use the u128. 

So for now I think I am going to stick with extprim based u128. If the rand crate implements Rand for u128 behind some feature flag I can look into this issue again.

**Comment by TimNN** [comment]
@robojeb: I'm curious, but why does `rand` need to support `u128` for you to use `u128` internally in the pcg implementation?

I think the request here was to just replace the use of `extprim::u128` with rust's native `u128` type.

**Comment by UnderTheCarpet** [comment]
For reference https://github.com/rust-lang-nursery/rand/pull/140

**Comment by robojeb** [comment]
The latest version of the crate now supports `u128` internals. 
The big blocker was `num-traits` support which lets me go to fully generic code instead of lots of macros. 

(Sorry I feel I am a bad maintainer, I am not used to being in charge and I have been popping in and out)
