### ISSUE TITLE
Port to rand_core 0.2

### ISSUE THREAD

**Issue by vks** [robojeb/pcg_rand#8]
I'm working on updating `pcg_rand` to use `rand_core` 0.2 (which corresponds to Rand 0.5) instead of Rand 0.4. Unfortunately, I ran into a compiler bug (https://github.com/rust-lang/rust/issues/43408). I'm not sure yet how to work around it.

**Comment by robojeb** [comment]
Hi @vks, I just pushed a new version based on the Rand 0.5. 
Does this work for you now?

**Comment by vks** [comment]
Looks good, thanks for the update!
