### ISSUE TITLE
Cannot use pcg_rand 0.9.2 without nightly

### ISSUE THREAD

**Issue by kennytm** [robojeb/pcg_rand#9]
886f85464762683f600426f48f84db88519a9fa9 added a `#![feature(tool_lints)]` which requires nightly to work, making it not possible to use 0.9.2 on beta or stable

https://github.com/robojeb/pcg_rand/blob/93ff7d3064346cca31cdabf54c2d760e37514d31/src/lib.rs#L121

The `tool_lints` warning has been *canceled* by rust-lang/rust#54358 on the current 1.30 beta channel, so writing `#[allow(needless_pass_by_value)]` should be fine. 

BTW, the feature has been *stabilized* by rust-lang/rust#54870 on the current 1.31 nightly channel meaning you don't need `#![feature(tool_lints)]` to write `#[allow(clippy::needless_pass_by_value)]` either.

**Comment by robojeb** [comment]
That is my bad, I should learn to check against all (or more) supported rust versions. 

I have published `0.9.3` which should resolve this, it also moves `u128` support behind a default feature (in case people don't need/want it) and adds very early experimental serde support.

**Comment by robojeb** [comment]
The new version is published and should resolve this. 
Let me know if anything else is broken, ill do my best to fix it.
